name: ProtocolExtension
description: The perfect solution for adding custom content onto your server!
authors:
  - Olafcio
website: https://olafcio1.github.io
version: "${version}"
main: pl.olafcio.protocolextension.server.ProtocolExtension
api-version: "${minecraft_version}"
load: STARTUP
dependencies:
  server:
    packetevents:
      load: BEFORE
      required: true
      join-classpath: true
